### ISSUE TITLE
Update audit template schematron files on selection-tool

### ISSUE THREAD

**Issue by macintoshpie** [BuildingSync/BuildingSync-website#128]
For schema v2.3, update the schematron files here:
https://github.com/pnnl/assetscore-schematron-docs/tree/master/docs/Audit_Template

**Comment by kflemin** [comment]
there are more files at that link than I was expecting...do I only replace the NewYork Audit use case? or do I need to add new use cases?

**Comment by macintoshpie** [comment]
Oh you're right! I think we want to update the NY use case, and create a new one for SF. I'm not sure if we want to add the ASHRAE Audit level 2 one, @nllong thoughts?

**Comment by nllong** [comment]
Yup, update NY, add SF, and skip L2. We are going to have differing opinions on how L2 is implemented.

**Comment by kflemin** [comment]
done!
