### ISSUE TITLE
[3/31/2022] Reconciliation of BEDES mappings to BuildingSync

### ISSUE THREAD

**Issue by nllong** [BuildingSync/BuildingSync-website#153]
Go/No-Go: BEDES has mapped a portion to BuildingSync and BuildingSync has its own mapping. This task will resolve the differences between the two.	

Need to demonstrate that BEDES and BuildingSync are mapping consistently and leveraging the mapping manager.

**Comment by nllong** [comment]
Need to look into https://github.com/LBNL-ETA/BEDES-Manager

**Comment by laurenliz22** [comment]
- Mapping manager can be used as starting point
- Consider removing workflow dependency if possible?
