### ISSUE TITLE
Fix measure search on BuildingSync website

### ISSUE THREAD

**Issue by nllong** [BuildingSync/BuildingSync-website#154]
When searching for text within a measure, the results don't actually filter.

To recreate: 

* go here: https://buildingsync.net/measures/2.4.0/
* Add in 'water' to the search box
* No filtering...

**Comment by kflemin** [comment]
@nllong, are you sure there's no filtering?  don't press "enter" after typing "water". Just type water. I see the list change when I do that.

**Comment by nllong** [comment]
ooohh, if you hit "enter" it resets it. Maybe we should make a note not to do that. Or have it say filter or something...

**Comment by nllong** [comment]
It also looks like the filter isn't doing a great jorb. With `water` it shows this measure which does not any any `water` in it... 

![image](https://user-images.githubusercontent.com/1907354/148128066-798f81ff-4ed3-4bbc-863a-1cf73cf90865.png)

**Comment by kflemin** [comment]
@nllong that one has "wastewater" in it (first line)

**Comment by nllong** [comment]
haha, you win. I missed that.

**Comment by kflemin** [comment]
yessssssss

**Comment by kflemin** [comment]
i'll add something about not pressing "enter" though
