### ISSUE TITLE
[1/25/22] Update BEDES mapping

### ISSUE THREAD

**Issue by macintoshpie** [BuildingSync/BuildingSync-website#161]
Blocked by #156
Updated mapping in [here](https://docs.google.com/spreadsheets/d/1dEY8LcwL_B04hNz77O7rekq1rN7i8NxqRQAWbkppQE8/edit?usp=sharing)

**Comment by macintoshpie** [comment]
@kflemin to review doc above

**Comment by kflemin** [comment]
done!
